site_name: Houses
site_url: https://sitename.example
theme:
  name: material
  
  font: 
    text: Stoke
    code: Montserrat

  features:
    - navigation.footer
  
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
    
    # Forest Mode (uses extra.css defined styles)
#    - scheme: forest
#      toggle:
#        icon: material/forest
#        name: Forest Mode

extra_css:
  - stylesheets/extra.css
    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2017 Ryan Jennings